"""update glossary 2

Revision ID: 6a9bca328d58
Revises: 1f51817f31d3
Create Date: 2026-07-06 15:11:47.868466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9bca328d58'
down_revision: Union[str, Sequence[str], None] = '1f51817f31d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glossary', 'term',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=748),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glossary', 'term',
               existing_type=sa.String(length=748),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
