"""remove_technology_id_from_cases

Revision ID: b6676b82b431
Revises: 9f49f816e922
Create Date: 2026-07-03 14:43:10.650845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6676b82b431'
down_revision: Union[str, Sequence[str], None] = '9f49f816e922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cases_technology_id_fkey'), 'cases', type_='foreignkey')
    op.drop_column('cases', 'technology_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('technology_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cases_technology_id_fkey'), 'cases', 'technologies', ['technology_id'], ['id'])
    # ### end Alembic commands ###
