"""add_technology_id_to_glossary

Revision ID: d7b7a9e76783
Revises: 2001eee32980
Create Date: 2026-07-06 12:25:37.732051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b7a9e76783'
down_revision: Union[str, Sequence[str], None] = '2001eee32980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glossary', sa.Column('technology_id', sa.Integer(), nullable=True))
    op.alter_column('glossary', 'definition',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'glossary', ['technology_id'])
    op.create_foreign_key(None, 'glossary', 'technologies', ['technology_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'glossary', type_='foreignkey')
    op.drop_constraint(None, 'glossary', type_='unique')
    op.alter_column('glossary', 'definition',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('glossary', 'technology_id')
    # ### end Alembic commands ###
